# Generated by Django 5.2 on 2025-04-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animales'},
        ),
        migrations.AlterModelOptions(
            name='historial',
            options={'verbose_name': 'Historial', 'verbose_name_plural': 'Historiales'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de ingreso'),
        ),
    ]
