# Generated by Django 5.2 on 2025-05-26 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0003_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_colegiado', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_administrador',
        ),
        migrations.AddField(
            model_name='animal',
            name='adoptante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adopciones.usuario'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='centro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adopciones.centro'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='usuario_simple',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adopciones.usuario'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='administrador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adopciones.administrador'),
        ),
        migrations.AddField(
            model_name='historial',
            name='veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adopciones.veterinario'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='veterinario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adopciones.veterinario'),
        ),
    ]
