# Generated by Django 5.2 on 2025-05-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0004_administrador_veterinario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='correo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default='No especificado', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_postal',
            field=models.CharField(default='00000', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='000000000', max_length=20),
        ),
    ]
