# Generated by Django 5.2 on 2025-05-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0005_remove_usuario_correo_usuario_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='animales/', verbose_name='Foto del animal'),
        ),
    ]
