# Generated by Django 5.2 on 2025-05-27 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0006_animal_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.animal')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.veterinario')),
            ],
        ),
    ]
