# Generated by Django 5.2 on 2025-05-27 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0007_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.animal')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.veterinario')),
            ],
        ),
    ]
