# Generated by Django 5.2 on 2025-05-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0009_medicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='en_tratamiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='pendiente_vacuna',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='urgente',
            field=models.BooleanField(default=False),
        ),
    ]
