# Generated by Django 5.2 on 2025-05-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0010_animal_en_tratamiento_animal_pendiente_vacuna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='fecha_adopcion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de adopción'),
        ),
    ]
