# Generated by Django 5.2 on 2025-05-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0011_animal_fecha_adopcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='fecha_adopcion',
        ),
    ]
